### ISSUE TITLE
need a method to truncate a double to a float

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#48] opened 2012-10-15 12:13 UTC
All Javascript numbers are 64-bit "doubles". Therefore, to emulate float support, we can do all our math on doubles, and then cut them down to size at the end of every operation.

Therefore we need a:
`var floatFromDouble = function(_input) { //more here }`

Research: [IEEE floating point format](http://en.wikipedia.org/wiki/IEEE_floating_point)

**Comment by guptha-** [comment] 2012-10-17 00:12
I have added the function to util.js. I have tested to some extent, but would like someone else to unit test too.

**Comment by jjfiv** [comment] 2012-10-17 00:19
Awesome!

Can you put some of your tests into `assert(cond, explanation)` expressions at the bottom of this file? (This will preserve your tests and give an example of how to use it to the next person)

Thanks,
John

**Comment by guptha-** [comment] 2012-10-17 01:22
Added. Not sure how to test the assert cases. Do we have any framework for
them ready or should I plug in the html for that?

**Comment by jjfiv** [comment] 2012-10-17 01:25
You should be able to open either html file (they both include 
`util.js`), and see any failures in the console.

I drop this in, once in a while, if I don't think the output is appearing:
`assert(false, "Just to test");`

**Comment by guptha-** [comment] 2012-10-17 02:53
Thanks. Verified it. This issue can be marked as closed once you verify
that the function works as intended.

**Comment by guptha-** [comment] 2012-10-20 20:36
As this has the same status as the bytestream to float/double issue, I am closing it with the caveat that it may not be entirely bug free as no one other than me has unit tested it.

**Closed as completed by guptha-** 2012-10-20 20:36 UTC
Labels: floating-point
